### ISSUE TITLE
uninitialized constant Fog::OpenStack::Storage

### ISSUE THREAD

**Issue by mickael-palma-argus** [chaadow/activestorage-openstack#19]
Hi,

I'm cannot debug this.

My gem file :
```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

gem 'activestorage-openstack'
gem 'bootsnap', require: false
gem 'fast_jsonapi'
gem 'pg', '~> 0.21.0'
gem 'puma'
gem 'rack-cors', require: 'rack/cors'
gem 'rails'
gem 'redis'
gem 'sidekiq'
gem 'tzinfo-data'

group :development, :test do
  gem 'awesome_print'
  gem 'byebug'
  gem 'factory_bot_rails'
  gem 'listen'
  gem 'rspec-rails'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen'
end

group :test do
  gem 'coderay'
  gem 'database_cleaner'
  gem 'fuubar'
  gem 'guard'
  gem 'guard-brakeman'
  gem 'guard-bundler'
  gem 'guard-reek'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'jsonapi-resources-matchers'
  gem 'reek'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'simplecov'
  gem 'vcr'
  gem 'webmock'
end

group :production do
  gem 'newrelic_rpm'
  gem 'rails_12factor'
end
```

in the storage.yml

```
openstack_config: &openstack_config
  service: OpenStack
  credentials:
    openstack_auth_url: <%= ENV.fetch('OPENSTACK_AUTH_URL') %>
    openstack_username: <%= ENV.fetch('OPENSTACK_USERNAME') %>
    openstack_api_key: <%= ENV.fetch('OPENSTACK_API_KEY') %>
    openstack_region: <%= ENV.fetch('OPENSTACK_REGION') %>
    openstack_temp_url_key: <%= ENV.fetch('OPENSTACK_TEMP_URL_KEY') %> # Mandatory, instructions below
  # connection_options: # optional
  #   chunk_size: 2097152 # 2MBs - 1MB is the default

production_openstack:
  <<: *openstack_config
  container: media-api

test_openstack:
  <<: *openstack_config
  container: test-media-api
```

I use in the environments file:
```
config.active_storage.service = :test_openstack
```

and my application.rb:
```
require_relative 'boot'

require 'rails'
# Pick the frameworks you want:
require 'active_model/railtie'
require 'active_job/railtie'
require 'active_record/railtie'
require 'active_storage/engine'
require 'action_controller/railtie'
require 'action_mailer/railtie'
require 'action_view/railtie'
require 'action_cable/engine'
# require 'sprockets/railtie'
require 'rails/test_unit/railtie'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module App
  # Defines main application behaviour.
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated
    # Rails version.
    config.load_defaults 5.2

    # Settings in config/environments/* take precedence over those
    # specified here.
    # Application configuration can go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded after
    # loading the framework and any gems in your application.

    # Only loads a smaller set of middleware suitable for API only apps.
    # Middleware like session, flash, cookies can be added back manually.
    # Skip views, helpers and assets when generating a new resource.
    config.api_only = true
  end
end
```

Can you help me fix this?

Regards
